VERSION 1.0 CLASS
BEGIN
  MultiUse = -1  'True
END
Attribute VB_Name = "IVBAEqualityComparer"
Attribute VB_GlobalNameSpace = False
Attribute VB_Creatable = False
Attribute VB_PredeclaredId = False
Attribute VB_Exposed = True
'@Exposed
Option Explicit
'@Folder("Lapis")

'Interface defines methods to support the comparison of objects for equality.


' Determines whether the specified objects are equal.
Public Function Equals(ByVal x As Variant, ByVal y As Variant) As Boolean
End Function


